[webserver]
port = ":8083"

[cache]
type="file"
basepath="./cache"

# register data providers
[[providers]]
name = "postgis"           # provider name is referenced from map layers
type = "postgis"        # the type of data provider. currently only supports postgis
host = "junction2k19-db-aarnio-b109.aivencloud.com"      # postgis database host
port = 16910             # postgis database port
database = "test"       # postgis database name
user = "avnadmin"         # postgis database user
password = "nokmwq63rc6seyjs"           # postgis database password
ssl_mode = "require"
max_connections = 150
# srid =              # The default srid for this provider. If not provided it will be WebMercator (3857)

  [[providers.layers]]
  name = "kansallispuisto"
  geometry_fieldname = "wkb_geometry"
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsBinary(wkb_geometry) AS wkb_geometry, kohdeluokk, ogc_fid FROM public.kansallispuistot WHERE wkb_geometry && !BBOX!"

  [[providers.layers]]
  name = "testipiste"
  geometry_fieldname = "geom"
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsBinary(geom) AS geom, visits, ogc_fid FROM public.distinct_named_locations WHERE geom && !BBOX!"

  [[providers.layers]]
  name = "monthly1"
  geometry_fieldname = "geom"
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsBinary(geom) AS geom, visits, ogc_fid FROM public.monthly_visits_2 WHERE month = 1 AND geom && !BBOX!"

  [[providers.layers]]
  name = "monthly2"
  geometry_fieldname = "geom"
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsBinary(geom) AS geom, visits, ogc_fid FROM public.monthly_visits_2 WHERE month = 2 AND geom && !BBOX!"

  [[providers.layers]]
  name = "monthly3"
  geometry_fieldname = "geom"
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsBinary(geom) AS geom, visits, ogc_fid FROM public.monthly_visits_2 WHERE month = 3 AND geom && !BBOX!"

  [[providers.layers]]
  name = "monthly4"
  geometry_fieldname = "geom"
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsBinary(geom) AS geom, visits, ogc_fid FROM public.monthly_visits_2 WHERE month = 4 AND geom && !BBOX!"

  [[providers.layers]]
  name = "monthly5"
  geometry_fieldname = "geom"
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsBinary(geom) AS geom, visits, ogc_fid FROM public.monthly_visits_2 WHERE month = 5 AND geom && !BBOX!"

  [[providers.layers]]
  name = "monthly6"
  geometry_fieldname = "geom"
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsBinary(geom) AS geom, visits, ogc_fid FROM public.monthly_visits_2 WHERE month = 6 AND geom && !BBOX!"

  [[providers.layers]]
  name = "monthly7"
  geometry_fieldname = "geom"
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsBinary(geom) AS geom, visits, ogc_fid FROM public.monthly_visits_2 WHERE month = 7 AND geom && !BBOX!"

  [[providers.layers]]
  name = "monthly8"
  geometry_fieldname = "geom"
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsBinary(geom) AS geom, visits, ogc_fid FROM public.monthly_visits_2 WHERE month = 8 AND geom && !BBOX!"

  [[providers.layers]]
  name = "monthly9"
  geometry_fieldname = "geom"
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsBinary(geom) AS geom, visits, ogc_fid FROM public.monthly_visits_2 WHERE month = 9 AND geom && !BBOX!"

  [[providers.layers]]
  name = "monthly10"
  geometry_fieldname = "geom"
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsBinary(geom) AS geom, visits, ogc_fid FROM public.monthly_visits_2 WHERE month = 10 AND geom && !BBOX!"

  [[providers.layers]]
  name = "monthly11"
  geometry_fieldname = "geom"
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsBinary(geom) AS geom, visits, ogc_fid FROM public.monthly_visits_2 WHERE month = 11 AND geom && !BBOX!"

  [[providers.layers]]
  name = "monthly12"
  geometry_fieldname = "geom"
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsBinary(geom) AS geom, visits, ogc_fid FROM public.monthly_visits_2 WHERE month = 12 AND geom && !BBOX!"


  [[providers.layers]]
  name = "daily0"
  geometry_fieldname = "geom"
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsBinary(geom) AS geom, visits, ogc_fid FROM public.daily_visits_3 WHERE day = 0 AND geom && !BBOX!"

  [[providers.layers]]
  name = "daily1"
  geometry_fieldname = "geom"
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsBinary(geom) AS geom, visits, ogc_fid FROM public.daily_visits_3 WHERE day = 0 AND geom && !BBOX!"

  [[providers.layers]]
  name = "daily2"
  geometry_fieldname = "geom"
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsBinary(geom) AS geom, visits, ogc_fid FROM public.daily_visits_3 WHERE day = 0 AND geom && !BBOX!"

  [[providers.layers]]
  name = "daily3"
  geometry_fieldname = "geom"
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsBinary(geom) AS geom, visits, ogc_fid FROM public.daily_visits_3 WHERE day = 0 AND geom && !BBOX!"

  [[providers.layers]]
  name = "daily4"
  geometry_fieldname = "geom"
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsBinary(geom) AS geom, visits, ogc_fid FROM public.daily_visits_3 WHERE day = 0 AND geom && !BBOX!"

  [[providers.layers]]
  name = "daily5"
  geometry_fieldname = "geom"
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsBinary(geom) AS geom, visits, ogc_fid FROM public.daily_visits_3 WHERE day = 0 AND geom && !BBOX!"

  [[providers.layers]]
  name = "daily6"
  geometry_fieldname = "geom"
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsBinary(geom) AS geom, visits, ogc_fid FROM public.daily_visits_3 WHERE day = 0 AND geom && !BBOX!"


  [[providers.layers]]
  name = "hour0"
  geometry_fieldname = "geom"
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsBinary(geom) AS geom, visits, ogc_fid FROM public.hourly_visits_3 WHERE hour = 0 AND geom && !BBOX!"
  [[providers.layers]]
  name = "hour1"
  geometry_fieldname = "geom"
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsBinary(geom) AS geom, visits, ogc_fid FROM public.hourly_visits_3 WHERE hour = 1 AND geom && !BBOX!"
  [[providers.layers]]
  name = "hour2"
  geometry_fieldname = "geom"
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsBinary(geom) AS geom, visits, ogc_fid FROM public.hourly_visits_3 WHERE hour = 2 AND geom && !BBOX!"
  [[providers.layers]]
  name = "hour3"
  geometry_fieldname = "geom"
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsBinary(geom) AS geom, visits, ogc_fid FROM public.hourly_visits_3 WHERE hour = 3 AND geom && !BBOX!"
  [[providers.layers]]
  name = "hour4"
  geometry_fieldname = "geom"
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsBinary(geom) AS geom, visits, ogc_fid FROM public.hourly_visits_3 WHERE hour = 4 AND geom && !BBOX!"
  [[providers.layers]]
  name = "hour5"
  geometry_fieldname = "geom"
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsBinary(geom) AS geom, visits, ogc_fid FROM public.hourly_visits_3 WHERE hour = 5 AND geom && !BBOX!"
  [[providers.layers]]
  name = "hour6"
  geometry_fieldname = "geom"
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsBinary(geom) AS geom, visits, ogc_fid FROM public.hourly_visits_3 WHERE hour = 6 AND geom && !BBOX!"
  [[providers.layers]]
  name = "hour7"
  geometry_fieldname = "geom"
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsBinary(geom) AS geom, visits, ogc_fid FROM public.hourly_visits_3 WHERE hour = 7 AND geom && !BBOX!"
  [[providers.layers]]
  name = "hour8"
  geometry_fieldname = "geom"
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsBinary(geom) AS geom, visits, ogc_fid FROM public.hourly_visits_3 WHERE hour = 8 AND geom && !BBOX!"
  [[providers.layers]]
  name = "hour9"
  geometry_fieldname = "geom"
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsBinary(geom) AS geom, visits, ogc_fid FROM public.hourly_visits_3 WHERE hour = 9 AND geom && !BBOX!"
  [[providers.layers]]
  name = "hour10"
  geometry_fieldname = "geom"
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsBinary(geom) AS geom, visits, ogc_fid FROM public.hourly_visits_3 WHERE hour = 10 AND geom && !BBOX!"
  [[providers.layers]]
  name = "hour11"
  geometry_fieldname = "geom"
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsBinary(geom) AS geom, visits, ogc_fid FROM public.hourly_visits_3 WHERE hour = 11 AND geom && !BBOX!"
  [[providers.layers]]
  name = "hour12"
  geometry_fieldname = "geom"
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsBinary(geom) AS geom, visits, ogc_fid FROM public.hourly_visits_3 WHERE hour = 12 AND geom && !BBOX!"
  [[providers.layers]]
  name = "hour13"
  geometry_fieldname = "geom"
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsBinary(geom) AS geom, visits, ogc_fid FROM public.hourly_visits_3 WHERE hour = 13 AND geom && !BBOX!"
  [[providers.layers]]
  name = "hour14"
  geometry_fieldname = "geom"
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsBinary(geom) AS geom, visits, ogc_fid FROM public.hourly_visits_3 WHERE hour = 14 AND geom && !BBOX!"
  [[providers.layers]]
  name = "hour15"
  geometry_fieldname = "geom"
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsBinary(geom) AS geom, visits, ogc_fid FROM public.hourly_visits_3 WHERE hour = 15 AND geom && !BBOX!"
  [[providers.layers]]
  name = "hour16"
  geometry_fieldname = "geom"
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsBinary(geom) AS geom, visits, ogc_fid FROM public.hourly_visits_3 WHERE hour = 16 AND geom && !BBOX!"
  [[providers.layers]]
  name = "hour17"
  geometry_fieldname = "geom"
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsBinary(geom) AS geom, visits, ogc_fid FROM public.hourly_visits_3 WHERE hour = 17 AND geom && !BBOX!"
  [[providers.layers]]
  name = "hour18"
  geometry_fieldname = "geom"
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsBinary(geom) AS geom, visits, ogc_fid FROM public.hourly_visits_3 WHERE hour = 18 AND geom && !BBOX!"
  [[providers.layers]]
  name = "hour19"
  geometry_fieldname = "geom"
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsBinary(geom) AS geom, visits, ogc_fid FROM public.hourly_visits_3 WHERE hour = 19 AND geom && !BBOX!"
  [[providers.layers]]
  name = "hour20"
  geometry_fieldname = "geom"
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsBinary(geom) AS geom, visits, ogc_fid FROM public.hourly_visits_3 WHERE hour = 20 AND geom && !BBOX!"
  [[providers.layers]]
  name = "hour21"
  geometry_fieldname = "geom"
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsBinary(geom) AS geom, visits, ogc_fid FROM public.hourly_visits_3 WHERE hour = 21 AND geom && !BBOX!"
  [[providers.layers]]
  name = "hour22"
  geometry_fieldname = "geom"
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsBinary(geom) AS geom, visits, ogc_fid FROM public.hourly_visits_3 WHERE hour = 22 AND geom && !BBOX!"
  [[providers.layers]]
  name = "hour23"
  geometry_fieldname = "geom"
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsBinary(geom) AS geom, visits, ogc_fid FROM public.hourly_visits_3 WHERE hour = 23 AND geom && !BBOX!"



  [[providers.layers]]
  name = "polku"
  geometry_fieldname = "wkb_geometry"
  id_fieldname = "ogc_fid"
  sql = "SELECT ST_AsBinary(wkb_geometry) AS wkb_geometry, ogc_fid FROM public.polut2 WHERE wkb_geometry && !BBOX!"

[[maps]]
name = "postgis"

  [[maps.layers]]
  provider_layer = "postgis.kansallispuisto"
  min_zoom = 0
  max_zoom = 20


  [[maps.layers]]
  provider_layer = "postgis.testipiste"
  min_zoom = 0
  max_zoom = 20

  [[maps.layers]]
  provider_layer = "postgis.monthly1"
  min_zoom = 0
  max_zoom = 20
  [[maps.layers]]
  provider_layer = "postgis.monthly2"
  min_zoom = 0
  max_zoom = 20
  [[maps.layers]]
  provider_layer = "postgis.monthly3"
  min_zoom = 0
  max_zoom = 20
  [[maps.layers]]
  provider_layer = "postgis.monthly4"
  min_zoom = 0
  max_zoom = 20
  [[maps.layers]]
  provider_layer = "postgis.monthly5"
  min_zoom = 0
  max_zoom = 20
  [[maps.layers]]
  provider_layer = "postgis.monthly6"
  min_zoom = 0
  max_zoom = 20
  [[maps.layers]]
  provider_layer = "postgis.monthly7"
  min_zoom = 0
  max_zoom = 20
  [[maps.layers]]
  provider_layer = "postgis.monthly8"
  min_zoom = 0
  max_zoom = 20
  [[maps.layers]]
  provider_layer = "postgis.monthly9"
  min_zoom = 0
  max_zoom = 20
  [[maps.layers]]
  provider_layer = "postgis.monthly10"
  min_zoom = 0
  max_zoom = 20
  [[maps.layers]]
  provider_layer = "postgis.monthly11"
  min_zoom = 0
  max_zoom = 20
  [[maps.layers]]
  provider_layer = "postgis.monthly12"
  min_zoom = 0
  max_zoom = 20


  [[maps.layers]]
  provider_layer = "postgis.daily0"
  min_zoom = 0
  max_zoom = 20
  [[maps.layers]]
  provider_layer = "postgis.daily1"
  min_zoom = 0
  max_zoom = 20
  [[maps.layers]]
  provider_layer = "postgis.daily2"
  min_zoom = 0
  max_zoom = 20
  [[maps.layers]]
  provider_layer = "postgis.daily3"
  min_zoom = 0
  max_zoom = 20
  [[maps.layers]]
  provider_layer = "postgis.daily4"
  min_zoom = 0
  max_zoom = 20
  [[maps.layers]]
  provider_layer = "postgis.daily5"
  min_zoom = 0
  max_zoom = 20
  [[maps.layers]]
  provider_layer = "postgis.daily6"
  min_zoom = 0
  max_zoom = 20


  [[maps.layers]]
  provider_layer = "postgis.hour0"
  min_zoom = 0
  max_zoom = 20
  [[maps.layers]]
  provider_layer = "postgis.hour1"
  min_zoom = 0
  max_zoom = 20
  [[maps.layers]]
  provider_layer = "postgis.hour2"
  min_zoom = 0
  max_zoom = 20
  [[maps.layers]]
  provider_layer = "postgis.hour3"
  min_zoom = 0
  max_zoom = 20
  [[maps.layers]]
  provider_layer = "postgis.hour4"
  min_zoom = 0
  max_zoom = 20
  [[maps.layers]]
  provider_layer = "postgis.hour5"
  min_zoom = 0
  max_zoom = 20
  [[maps.layers]]
  provider_layer = "postgis.hour6"
  min_zoom = 0
  max_zoom = 20
  [[maps.layers]]
  provider_layer = "postgis.hour7"
  min_zoom = 0
  max_zoom = 20
  [[maps.layers]]
  provider_layer = "postgis.hour8"
  min_zoom = 0
  max_zoom = 20
  [[maps.layers]]
  provider_layer = "postgis.hour9"
  min_zoom = 0
  max_zoom = 20
  [[maps.layers]]
  provider_layer = "postgis.hour10"
  min_zoom = 0
  max_zoom = 20
  [[maps.layers]]
  provider_layer = "postgis.hour11"
  min_zoom = 0
  max_zoom = 20
  [[maps.layers]]
  provider_layer = "postgis.hour12"
  min_zoom = 0
  max_zoom = 20
  [[maps.layers]]
  provider_layer = "postgis.hour13"
  min_zoom = 0
  max_zoom = 20
  [[maps.layers]]
  provider_layer = "postgis.hour14"
  min_zoom = 0
  max_zoom = 20
  [[maps.layers]]
  provider_layer = "postgis.hour15"
  min_zoom = 0
  max_zoom = 20
  [[maps.layers]]
  provider_layer = "postgis.hour16"
  min_zoom = 0
  max_zoom = 20
  [[maps.layers]]
  provider_layer = "postgis.hour17"
  min_zoom = 0
  max_zoom = 20
  [[maps.layers]]
  provider_layer = "postgis.hour18"
  min_zoom = 0
  max_zoom = 20
  [[maps.layers]]
  provider_layer = "postgis.hour19"
  min_zoom = 0
  max_zoom = 20
  [[maps.layers]]
  provider_layer = "postgis.hour20"
  min_zoom = 0
  max_zoom = 20
  [[maps.layers]]
  provider_layer = "postgis.hour21"
  min_zoom = 0
  max_zoom = 20
  [[maps.layers]]
  provider_layer = "postgis.hour22"
  min_zoom = 0
  max_zoom = 20
  [[maps.layers]]
  provider_layer = "postgis.hour23"
  min_zoom = 0
  max_zoom = 20


  [[maps.layers]]
  provider_layer = "postgis.polku"
  min_zoom = 0
  max_zoom = 20
